const englishWords = [
  // 2026/1/26 更新单词卡片数据对象
  {
    word: "combine",
    pronunciation: "/kəm'baɪn/",
    meaning: "v. 结合，联合",
    example:
      "Some people combine shopping with visits to the town's restaurants and cafes",
    translation: "一些人在前往城镇的餐厅和咖啡厅的同时进行购物。",
  },
  {
    word: "primary",
    pronunciation: "/'praɪmeri/",
    meaning:
      "adj. 首要的，主要的；最初的；原本的；第一手的, 直接的；初级的, 小学的；初等的 n. 初选者；原色",
    example:
      "The primary aim of this course is to improve your spoken English.",
    translation: "这门课的主要目的是提高英语会话能力。",
  },
  {
    word: "cue",
    pronunciation: "/kjuː/",
    meaning: "n. 暗示，提示",
    example: "They started washing up, so that was our cue to leave.",
    translation: "他们开始洗刷碗碟了，这就是在暗示我们该离开了。",
  },
  {
    word: "illuminate",
    pronunciation: "/ɪ'luːmɪneɪt/",
    meaning: "v. 照明，照射；阐释，说明；用彩灯装饰；使精神焕发",
    example: "The earth is illuminated by the sun.",
    translation: "太阳照亮地球。",
  },
  {
    word: "formulate",
    pronunciation: "/'fɔːrmjuleɪt/",
    meaning: "v. 制订，规划，构想；确切表达，认真阐述",
    example: "He struggled to formulate an answer.",
    translation: "他试图去构想一个答案。",
  },
  {
    word: "approximate",
    pronunciation: "/ə'prɑːksɪmət/",
    meaning: "adj. 大约的，近似的 v. 接近，约等于",
    example: "The approximate cost was 100 dollars.",
    translation: "花费大概是100美元。",
  },
  {
    word: "affect",
    pronunciation: "/ə'fekt/",
    meaning: "v. 影响；感染",
    example: "Your opinion will not affect my decision.",
    translation: "你的意见不会影响我的决定。",
  },
  {
    word: "signal",
    pronunciation: "/'sɪɡnəl/",
    meaning:
      "n. 信号，暗号；迹象；信号灯 v. 发信号，示意；显示，表示 adj. 显著的，不寻常的",
    example: "a danger/warning/distress etc. signal",
    translation: "危险、警告、求救等信号",
  },
  {
    word: "county",
    pronunciation: "/'kaʊnti/",
    meaning: "n. （英）郡，（美）县",
    example: "A county usually consists of several towns and rural areas.",
    translation: "郡通常由几个镇以及乡村地区组成。",
  },
  {
    word: "behave",
    pronunciation: "/bɪ'heɪv/",
    meaning: "v. 表现；守规矩，举止得体",
    example: "They behaved very badly towards their guests.",
    translation: "他们对客人们很不礼貌。",
  },
  {
    word: "indicate",
    pronunciation: "/'ɪndɪkeɪt/",
    meaning: "v. 显示，表明；暗示；是…的标志，象征",
    example:
      "Record profits in the retail market indicate a boom in the economy.",
    translation: "零售市场上有史以来的最高利润显示出经济的突飞猛进。",
  },
  {
    word: "occur",
    pronunciation: "/ə'kɜːr/",
    meaning: "v. 发生；出现",
    example: "When exactly did the incident occur?",
    translation: "这一事件究竟是什么时候发生的？",
  },
  {
    word: "flush",
    pronunciation: "/flʌʃ/",
    meaning:
      "v. 冲洗；发红，脸红 n. 脸红；一阵强烈情感 adj. 完全齐平的；富有的",
    example: "They flushed the toilet paper down the toilet.",
    translation: "他们用马桶把厕纸冲走了。",
  },
  {
    word: "vision",
    pronunciation: "/'vɪʒn/",
    meaning: "n. 视觉，视力；幻想，幻觉；远见",
    example: "It came within my range of vision.",
    translation: "它进入了我的视野。",
  },
  {
    word: "blade",
    pronunciation: "/bleɪd/",
    meaning: "n. 刀片；桨叶；草叶",
    example: "The blade of the sword flashed in the moonlight.",
    translation: "月光下剑锋闪闪发亮。",
  },
  {
    word: "bid",
    pronunciation: "/bɪd/",
    meaning: "n. 出价；投标；努力争取 v. 出价；投标；吩咐；努力争取",
    example:
      "Several firms have bid for the contract to build the new concert hall.",
    translation: "有几家公司投标，争取建造新音乐厅的合同。",
  },
  {
    word: "disrupt",
    pronunciation: "/dɪs'rʌpt/",
    meaning: "v. 使中断；扰乱",
    example: "Traffic was disrupted by a serious car accident.",
    translation: "一场严重的车祸扰乱了交通。",
  },
  {
    word: "massive",
    pronunciation: "/'mæsɪv/",
    meaning: "adj. 巨大的；大量的；厚重的；严重的",
    example: "The explosion made a massive hole in the ground.",
    translation: "爆炸在地面留下了一个巨大的坑。",
  },
  {
    word: "event",
    pronunciation: "/ɪ'vent/",
    meaning:
      "n. 大事, 事件；事情的进程；活动, 经历；结果, 后果；比赛项目；[物][统]事件",
    example: "In the light of later events the decision was proved right.",
    translation: "从后来发生的事看，这一决定证明是正确的。",
  },
  {
    word: "disapprove",
    pronunciation: "/ˌdɪsə'pruːv/",
    meaning: "v. 不赞成，反对",
    example: "I strongly disapprove of child marriage.",
    translation: "我强烈反对童婚。",
  },
  {
    word: "womb",
    pronunciation: "/wuːm/",
    meaning: "n. 子宫",
    example: "A mother's health can affect the baby in the womb.",
    translation: "母亲的健康会对子宫中的胎儿产生影响。",
  },
  {
    word: "pulley",
    pronunciation: "/'pʊli/",
    meaning: "n. 滑轮；滑车",
    example: "The sculpture was moved by ropes and pulleys.",
    translation: "这块雕像是用绳子和滑轮给移走的。",
  },
  {
    word: "label",
    pronunciation: "/'leɪbl/",
    meaning: "n. 标签，标记；称号 v. 贴标签于…；把…称为",
    example:
      "The rich madam never cares about price labels when she is shopping.",
    translation: "这位阔太太买东西时从不关心价格标签。",
  },
  {
    word: "engage",
    pronunciation: "/ɪn'ɡeɪdʒ/",
    meaning: "v. 吸引住；参与；订婚；与…建立密切关系；与（某人）交战",
    example: "Jack and Anne are engaged.",
    translation: "杰克和安妮订婚了。",
  },
  {
    word: "argument",
    pronunciation: "/'ɑːrɡjumənt/",
    meaning: "n. 争论；观点",
    example: "She got into an argument with the teacher.",
    translation: "她和老师争论了起来。",
  },
  {
    word: "mutual",
    pronunciation: "/'mjuːtʃuəl/",
    meaning: "adj. 共同的，相互的",
    example: "They share a mutual interest in sports.",
    translation: "他们对体育运动兴趣相投。",
  },
  {
    word: "intense",
    pronunciation: "/ɪn'tens/",
    meaning: "adj. 强烈的；紧张的；热情的",
    example: "This work demands intense concentration.",
    translation: "这项工作要求高度的专注力。",
  },
  {
    word: "circumstance",
    pronunciation: "/'sɜːrkəmstæns/",
    meaning: "n. 情况；情形；境况",
    example:
      "The company reserves the right to cancel this agreement in certain circumstances.",
    translation: "本公司保留在一定条件下取消这项协议的权利。",
  },
  {
    word: "contact",
    pronunciation: "/'kɑːntækt/",
    meaning: "n. 接触；联系 v. 联系（某人）",
    example: "He lost contact with his friends after graduation.",
    translation: "他自毕业后，就和他的朋友失去了联系。",
  },
  {
    word: "feature",
    pronunciation: "/'fiːtʃər/",
    meaning: "n. 特征，特色；相貌；特写 v. 以…为特色",
    example:
      "A distinctive feature of Indian movies is that they always contain dancing scenes.",
    translation: "印度电影的一个显著特征是里面有很多跳舞的桥段。",
  },
  {
    word: "molecule",
    pronunciation: "/'mɑːlɪkjuːl/",
    meaning: "n. 分子",
    example: "The molecules of oxygen contain two atoms.",
    translation: "氧分子含有两个原子。",
  },
  {
    word: "extension",
    pronunciation: "/ɪk'stenʃn/",
    meaning: "n. 扩大范围；延展，延伸；电话分机；延期",
    example: "a gradual extension of the powers of central government",
    translation: "中央政府权力的逐渐扩大",
  },
  // 2026/1/28 更新单词卡片数据对象
  {
    word: "occasion",
    pronunciation: "/ə'keɪʒn/",
    meaning: "n. 时刻，场合，机会，理由 vt. 引起，惹起",
    example: "They've met on several occasions to discuss the issue before.",
    translation: "他们之前会面讨论过几次这个问题。",
    appendInfo: [
      "on occasion 有时，不时；by occasion of 由于",
      "on one occasion：有一次；on another occasion: 还有一次",
    ],
  },
  {
    word: "gesture",
    pronunciation: "/'dʒestʃər/",
    meaning: "n. 手势；姿态 v. 打手势",
    example: "They communicated entirely by gesture.",
    translation: "他们完全通过手势来交流。",
  },
  {
    word: "motion",
    pronunciation: "/'moʊʃn/",
    meaning: "n. 运动；移动；动作",
    example: "The video is replayed in slow motion.",
    translation: "视频被慢动作回放。",
  },
  {
    word: "receiver",
    pronunciation: "/rɪ'siːvər/",
    meaning:
      "n. 收受者; 收件人; 接待者; (电话)听筒, 耳机; 收音机; (电视)接收机; 接收器; 接球手",
    example: "He put the receiver back to his ear.",
    translation: "他把听筒放回耳边。",
  },
  {
    word: "spot",
    pronunciation: "/spɑːt/",
    meaning:
      "n. 斑点; 污渍; 粉刺; 丘疹; 污点; 地点; 场所; 少量; 职位 v. 用斑点装饰; 使有污渍; 沾上污渍; 发现, 认出; 玷污 adj. 当场作出的; 现付的; 当即支付的; 抽样的; 从现场报道的; 插播的",
    example: "Which has spots, the leopard or the tiger?",
    translation: "有斑点的是豹还是虎？",
  },
  {
    word: "investigate",
    pronunciation: "/ɪn'vestɪɡeɪt/",
    meaning: "v. 调查，研究；审查",
    example: "Sherlock Holmes investigates problems carefully.",
    translation: "夏洛克·福尔摩斯仔细地调查问题。",
  },
  {
    word: "recipient",
    pronunciation: "/rɪ'sɪpiənt/",
    meaning: "n. 接受者，领受者",
    example:
      "Bob Dylan is the recipient of the Nobel Prize for Literature in 2016.",
    translation: "鲍勃·迪伦是2016年诺贝尔文学奖得主。",
  },
  {
    word: "involve",
    pronunciation: "/ɪn'vɑːlv/",
    meaning: "v. 使卷入，牵涉；包含",
    example:
      "The manager likes to be democratic by involving everyone in the decision making.",
    translation: "这位经理喜欢民主的方式，让每个人都参与决策制定。",
  },
  {
    word: "ignore",
    pronunciation: "/ɪɡ'nɔːr/",
    meaning: "v. 忽视，忽略",
    example: "I made a suggestion but they chose to ignore it.",
    translation: "我提了个建议，但他们不予理会。",
  },
  {
    word: "coordinate",
    pronunciation: "/koʊ'ɔːrdɪneɪt/",
    meaning: "v. 协调，整合； 使一致 n. 坐标；套装",
    example: "The nursing staff coordinate smoothly.",
    translation: "护理人员之间协同配合得很顺畅。",
    appendInfo: ["co(共同)+ordin(顺序)+ate(使…) → 顺序相同的 → 并列的"],
  },
  // 2026/1/29 更新单词卡片数据对象
  {
    word: "decade",
    pronunciation: "/'dekeɪd/",
    meaning: "n. 十年",
    example: "He spent last decade in a small town in China.",
    translation: "过去的十年里，他待在了中国的一个小镇上。",
    appendInfo: [
      "decade十年 century百年 millennium千年",
      "several decades 数十年",
    ],
  },
  {
    word: "focus",
    pronunciation: "/'foʊkəs/",
    meaning: "v. （使）聚焦 n. 焦点；中心",
    example: "The discussion focused on three main problems.",
    translation: "讨论集中在三个主要问题上。",
    appendInfo: ["focus(...)on/upon(使...)集中于..."],
  },
  {
    word: "offset",
    pronunciation: "/'ɔːfset/",
    meaning: "v. 抵消；弥补；补偿 adj. 胶印的，平板印刷的",
    example: "He raised the prices to offset the increased cost of materials.",
    translation: "他提高售价以补偿材料增加的成本。",
    appendInfo: [
      "offset the loss 弥补损失",
      "be offset by =compensate; compensate for 补偿",
    ],
  },
  {
    word: "huddle",
    pronunciation: "/'hʌdl/",
    meaning: "v. 挤作一团；聚集 n. 杂乱的一堆；聚在一起的一群人",
    example: "The girl huddled in a corner and started weeping.",
    translation: "这个女孩蜷缩在角落，哭了起来。",
    appendInfo: [
      "huddle up  集合，蜷缩",
      "huddle together 挤作一团 huddle up 卷缩",
    ],
  },
  {
    word: "turret",
    pronunciation: "/'tɜːrət/",
    meaning: "n. 塔楼，角塔",
    example: "Our house has a turret you can’t get into from inside.",
    translation: "我们这座房子有个角楼，从房子里面进不去。",
    appendInfo: ["tower->tur->塔    r->无义 et->表示小的后缀"],
  },
  {
    word: "attraction",
    pronunciation: "/ə'trækʃn/",
    meaning: "n. 吸引，吸引力；有吸引力的人或事物",
    example:
      "They fell in love so quickly for they had a very strong attraction towards each other.",
    translation: "他们一见钟情，因为他们对彼此都有很强的吸引力。",
    appendInfo: ["attract [ə'trækt]    vt. 吸引；引起 vi. 吸引；有吸引力"],
  },
  {
    word: "ecology",
    pronunciation: "/i'kɑːlədʒi/",
    meaning: "n. 生态；生态学",
    example: "Concern about ecology is a recent development.",
    translation: "对生态学的关心是最近才有的事。",
    appendInfo: ["ecological 生态学的、生态的", "biology n. 生物学"],
  },
  {
    word: "overall",
    pronunciation: "/ˌoʊvər'ɔːl/",
    meaning:
      "adv. 全部；总计；一般来说；大致上 n. 外套；罩衣；工装服；连身工作服 adj. 全面的；综合的；总体的",
    example:
      "There will be winners in each of three age groups, and one overall winner.",
    translation: "三个年龄组将各产生一名优胜者，另有一位总优胜者。",
    appendInfo: [
      "over(从头到尾)+all(所有的) → 全面的，综合的",
      "overalls 工作服",
    ],
  },
  {
    word: "former",
    pronunciation: "/'fɔːrmər/",
    meaning: "adj. 在前的 n. 前者",
    example: "the countries of the former Soviet Union",
    translation: "前苏联加盟共和国",
    appendInfo: [
      "former 前者 latter 后者",
      "form（形成）+er（人，物）——已形成的东西——在前的",
    ],
  },
  {
    word: "invalid",
    pronunciation: "/ɪn'vælɪd/",
    meaning:
      "adj. （法律上）无效的，不合法的；（观点）站不住脚的 n. 病人，久病衰弱者",
    example: "People with invalid papers are deported to another country.",
    translation: "持无效证件的人被驱逐到别国。",
    appendInfo: ["反义词 valid 有效的", "be invalided out 免除义务"],
  },
  // 2026/1/30
  {
    word: "crash",
    pronunciation: "/kræʃ/",
    meaning:
      "n. 崩溃；撞车，相撞；巨大声响；（飞机的）坠毁；（某物价值或价格的）暴跌；狂跌 v. 猛撞，撞击；发出巨响；崩溃；〔股市或股票〕狂跌，暴跌",
    example: "The great financial crash in 1929 ruined international trade.",
    translation: "1929年的经济大萧条摧毁了国际贸易.",
    appendInfo: ["crash into 与....相撞", "financial crash:金融危机"],
  },
  {
    word: "cell",
    pronunciation: "/sel/",
    meaning: "n. 细胞；牢房；手机",
    example: "the nucleus of a cell",
    translation: "细胞核",
    appendInfo: ["blood cell 血细胞", "prison /gaol /jail cell 牢房"],
  },
  {
    word: "output",
    pronunciation: "/'aʊtpʊt/",
    meaning: "n. 产量；输出信息，输出功率 v. 输出（信息）",
    example: "Manufacturing output has increased by 8%.",
    translation: "制造业产量增长了8%。",
    appendInfo: [],
  },
  {
    word: "migrant",
    pronunciation: "/'maɪɡrənt/",
    meaning: "n. 移居者；迁徙动物 adj. 迁移的；迁徙的",
    example:
      "Many migrant families face significant challenges when adjusting to life in a new country.",
    translation: "许多移民家庭在适应新国家的生活时面临重重挑战。",
    appendInfo: ["migrant workers（农民工）"],
  },
  {
    word: "consolation",
    pronunciation: "/ˌkɑːnsə'leɪʃn/",
    meaning: "n. 安慰；慰问",
    example:
      "If it's of any consolation to you, you are not the only one losing money",
    translation: "不仅仅只有你一个人损失了金钱，这也许能让你略感安慰。",
    appendInfo: ["console   v   安慰"],
  },
  {
    word: "teem",
    pronunciation: "/tiːm/",
    meaning: "v. 充满；大量出现；下大雨",
    example: "It's been teeming down all night.",
    translation: "倾盆大雨下了一整夜。",
    appendInfo: [],
  },
  {
    word: "collection",
    pronunciation: "/kə'lekʃn/",
    meaning: "n. 收藏品，收集物；收集，采集",
    example: "Tom's collection of oil paintings has been stolen.",
    translation: "汤姆收藏的油画失窃了。",
    appendInfo: [],
  },
  {
    word: "channel",
    pronunciation: "/'tʃænl/",
    meaning: "n. 海峡；频道；手段，渠道",
    example: "What's on Channel 4 tonight?",
    translation: "电视四台今晚有什么节目？",
    appendInfo: ["canal 运河 channel 海峡"],
  },
  {
    word: "calf",
    pronunciation: "/kæf/",
    meaning: "n. 牛犊，幼崽",
    example: "How many calves were given birth by the cow?",
    translation: "这只奶牛生了几只牛犊？",
    appendInfo: ["calves 复数"],
  },
  {
    word: "cylinder",
    pronunciation: "/'sɪlɪndər/",
    meaning: "n. 圆柱体；圆筒状物；（发动机的）气缸",
    example: "The cylinder is a crucial part of the washing machine.",
    translation: "滚筒是洗衣机必不可少的部分。",
    appendInfo: [
      "cycle → cyl ； inter → inder   cyl+inder →里面有一定空间的圆形 → 圆筒",
    ],
  },
  // 2026/2/2
  {
    word: "promote",
    pronunciation: "/prə'moʊt/",
    meaning: "v. 促进，提升；升迁；促销",
    example: "policies to promote economic growth",
    translation: "促进经济增长的政策",
    appendInfo: ["get promoted  升职", "advance近义词"],
  },
  {
    word: "associate",
    pronunciation: "/ə'soʊʃieɪt/",
    meaning:
      "v. 联系，联想 n. 同事；合作人；伙伴 adj. （等级或头衔）副的；准的",
    example: "I always associate the smell of baking with my childhood.",
    translation: "一闻到烘烤食物的味道我就想起了童年。",
    appendInfo: [
      "这些名词均有“同事，伙伴”之意。",
      "associate: 普通用词，侧重指在利害关系上密切相关。",
      "companion: 指陪伴他人的人，即同伴或陪伴。",
      "comrade: 指具有共同的事业、利益关系相一致的人。",
      "colleague: 一般用于对同事的正式称呼，基本上专用在职业关系上。",
      "fellow: 多用复数形式，指一块住、生活或同行共事的人。",
      "partner: 指事业中处于合伙关系的人，或指婚姻、游戏、跳舞中的另一方。",
    ],
  },
  {
    word: "bar",
    pronunciation: "/bɑːr/",
    meaning:
      "n. 条, 杆, 棒, 棍; 酒吧; 吧台; 栅, 栏, 障碍(物); 律师职业 v. 闩上; 阻拦, 拦住; 妨碍; 禁止 prep. 除…外",
    example: "We met at a bar called the Flamingo.",
    translation: "我们在一家名为“火烈鸟”的酒吧相遇。",
    appendInfo: ["bar none 独一无二"],
  },
  {
    word: "throughout",
    pronunciation: "/θruː'aʊt/",
    meaning: "prep. 遍及，贯穿  adv. 到处，自始至终",
    example: "The museum is open daily throughout the year.",
    translation: "这个博物馆一年到头每天都开放。",
    appendInfo: ["throughout the world", "穿过出口-就是贯穿"],
  },
  {
    word: "mechanism",
    pronunciation: "/'mekənɪzəm/",
    meaning: "n. 机械装置，机件；方法，机制；体制",
    example:
      "The college has established an effective student support mechanism.",
    translation: "这所大学已经建立了有效的学生支持机制。",
    appendInfo: ["mechanism 机械", "mechanical 机械的", "machine 机械"],
  },
  {
    word: "tend",
    pronunciation: "/tend/",
    meaning: "v. 倾向（于）；容易表现出（某种特性）；照料",
    example: "When I'm tired, I tend to make mistakes.",
    translation: "我累了就容易出错。",
    appendInfo: ["1.tend to do sth   通常是；往往会"],
  },
  {
    word: "category",
    pronunciation: "/'kætəɡɔːri/",
    meaning: "n. 种类，类别",
    example: "We are divided into several categories by grades.",
    translation: "按照成绩，我们被划分成好几个类别。",
    appendInfo: [],
  },
  {
    word: "beverage",
    pronunciation: "/'bevərɪdʒ/",
    meaning: "n. 饮料",
    example:
      "Alcoholic beverages can only be sold to adults according to the new law.",
    translation: "新颁布的法律规定酒精饮料仅向成年人出售。",
    appendInfo: ["bever(饮）+-age（名词后缀表集合）=所有饮用东西=饮料"],
  },
  {
    word: "mental",
    pronunciation: "/'mentl/",
    meaning: "adj. 精神的，心理的；脑力的 n. 精神病患者",
    example: "Do you have a mental picture of what it will look like?",
    translation: "在你脑子里它会是什么样子？",
    appendInfo: [
      "metal n.金属",
      "mentally ['mentəli] adv. 精神上，智力上；心理上",
    ],
  },
  {
    word: "flavour",
    pronunciation: "/'fleɪvər/",
    meaning:
      "n. （食物或饮料的）味道；特点，特色 v. 给（食物或饮料）调味；加味于",
    example:
      "Onions smell so awful that I can never stand the flavour of them.",
    translation: "洋葱太难闻了，我无法忍受它们的味道。",
    appendInfo: ["the flavour of.. ..的味道"],
  },
  // 2026/2/3
  {
    word: "relate",
    pronunciation: "/rɪ'leɪt/",
    meaning: "v. 找到联系，使互相联系；讲述，叙述",
    example: "In the future, pay increases will be related to productivity.",
    translation: "以后，工资的增加将和业绩挂钩。",
    appendInfo: [
      "relation [ri'leiʃən] n. 关系；亲属关系；叙述；故事",
      "relationship [ri'leiʃənʃip] n. 关联；关系",
    ],
  },
  {
    word: "flat",
    pronunciation: "/flæt/",
    meaning:
      "adj. 水平的；平坦的；平滑的；枯燥的；无趣的；缺乏热情的；不景气的；萧条的；生意清淡的（价格）固定的；瘪的；扁平的；平淡的；单调的；断然的；绝对的 n. 一套房间；公寓；单元房",
    example: "People used to think the earth was flat.",
    translation: "人们曾经认为地球是平的。",
    appendInfo: ["flat out精疲力竭, 疲惫的"],
  },
  {
    word: "transparent",
    pronunciation: "/træns'pærənt/",
    meaning: "adj. 透明的；明显的；（谎言、借口等）易识破的",
    example: "The insect's wings are almost transparent.",
    translation: "这昆虫的翅膀几乎是透明的。",
    appendInfo: ["transparent sincerity. 无比的坦诚"],
  },
  {
    word: "pressure",
    pronunciation: "/'preʃər/",
    meaning:
      "n. 压力，困扰；（物理上的）压力，压强；紧迫，催促 v. 对…施压，强迫",
    example: "The water pressure may need adjusting.",
    translation: "水压可能需要调整。",
    appendInfo: ["put pressure on sb to do 给某人压力，不得不做某事"],
  },
  {
    word: "slip",
    pronunciation: "/slɪp/",
    meaning: "v. 滑倒，滑落；溜走；下降，退步 n. 疏漏；纸片，纸条；摔倒",
    example: "As I ran up the stairs, my foot slipped and I fell.",
    translation: "我跑上楼梯时失脚摔倒了。",
    appendInfo: ["slip your mind/memory  被遗忘", "slip out 溜出去  "],
  },
  {
    word: "entire",
    pronunciation: "/ɪn'taɪər/",
    meaning: "adj. 全部的，整个的",
    example: "The entire village was destroyed.",
    translation: "整个村庄都给毁了。",
    appendInfo: [],
  },
  {
    word: "melt",
    pronunciation: "/melt/",
    meaning: "v. （使）融化；（使）溶解；（生气后）变得心软",
    example: "The snow that covered the city finally melted in the sun.",
    translation: "覆盖着整个城市的雪终于在阳光下融化了。",
    appendInfo: ["dissolve 溶解", "melt away: 消融, 散去"],
  },
  {
    word: "position",
    pronunciation: "/pə'zɪʃn/",
    meaning: "n. 位置；地位；职务；立场",
    example: "Where would be the best position for the lights?",
    translation: "这些灯装在什么位置最好？",
    appendInfo: [],
  },
  {
    word: "emergency",
    pronunciation: "/i'mɜːrdʒənsi/",
    meaning: "n. 紧急情况，不测事件",
    example:
      "The government has declared a state of emergency following the earthquake.",
    translation: "地震发生后政府已宣布进入紧急状态。",
    appendInfo: ["emergency room 急诊室"],
  },
  {
    word: "typical",
    pronunciation: "/'tɪpɪkl/",
    meaning: "adj. 典型的，有代表性的；不出所料的，一贯的",
    example: "This is a typical example of Roman pottery.",
    translation: "这是一件典型的罗马陶器。",
    appendInfo: [
      "typic adj. 典型的,象征性的",
      "tropical ['trɔpikəl] adj. 热带的；酷热的；热情的",
    ],
  },
  // 2026/2/4
  {
    word: "approach",
    pronunciation: "/ə'proʊtʃ/",
    meaning:
      "v. （在距离或时间上）靠近，接近；接洽；建议；要求；（在数额、水平或质量上）接近；着手处理；对付 n. （待人接物或思考问题的）方式，方法，态度；（距离和时间上的）靠近，接近；接洽；建议；通路；路径；道路",
    example: "We heard the sound of an approaching car.",
    translation: "一辆汽车驶近过来，我们听到了它的声音。",
    appendInfo: ["道路 the approach to ", "approach to sth 接近某物"],
  },
  {
    word: "display",
    pronunciation: "/dɪ'spleɪ/",
    meaning: "v. 展示；显示，表现 n. 显示，陈列",
    example:
      "The exhibition gives artists an opportunity to display their paintings.",
    translation: "这次展览给了画家展示画作的机会。",
    appendInfo: [],
  },
  {
    word: "stimulus",
    pronunciation: "/'stɪmjuləs/",
    meaning: "n. 刺激（物）；促进因素",
    example:
      "The government resorted to tax deductions as stimulus which the slow economy needed.",
    translation: "政府采取减税措施为不景气的经济带来了其所需的刺激。",
    appendInfo: [],
  },
  {
    word: "specific",
    pronunciation: "/spə'sɪfɪk/",
    meaning:
      "adj. 明确的, 确切的; 具体的; 特定的, 特有的 n. 特性, 特色; [复]详情, 细节",
    example: "I gave you specific instructions.",
    translation: "我给过你明确的指示。",
    appendInfo: ["specific title 特殊职位"],
  },
  {
    word: "pattern",
    pronunciation: "/'pætərn/",
    meaning:
      "n. 图案, 花样, 式样; (事情发生、发展、完成的) 模式, 方式, 形式; 模范, 典范, 榜样; [用以制作某物的]模型; (服装的) 纸样 v. 仿制, 仿造; 模仿; 以图案装饰; 形成图案",
    example: "The curtains had a beautiful pattern of flowers.",
    translation: "窗帘上绘有精美的花卉图案。",
    appendInfo: [],
  },
  {
    word: "reward",
    pronunciation: "/rɪ'wɔːrd/",
    meaning: "n. 奖赏；报酬，报偿 v. 奖赏；报答",
    example: "a reward for good behaviour",
    translation: "优秀行为奖",
    appendInfo: ["习惯用语：as a reward for 作为（对某事的）报酬"],
  },
  {
    word: "persist",
    pronunciation: "/pər'sɪst/",
    meaning: "v. 坚持；执意，执着；维持，持续",
    example: "The cold weather will persist for the rest of the week.",
    translation: "这种寒冷的天气将持续到本周末。",
    appendInfo: [],
  },
  {
    word: "link",
    pronunciation: "/lɪŋk/",
    meaning: "n. 联系，纽带 v. 连接，联系",
    example: "Police suspect there may be a link between the two murders.",
    translation: "警方怀疑那两桩凶杀案可能有关联。",
    appendInfo: [
      "link up with =connect with 与。。。。相连接，通常水域相同用link up with 车辆，道路交通相连用connet with ",
    ],
  },
  {
    word: "maintain",
    pronunciation: "/meɪn'teɪn/",
    meaning: "v. 维持; 维修, 保养; 赡养, 负担, 支持; 主张, 断言; 保卫, 守住",
    example: "We have to maintain the room orderly and clean all the time.",
    translation: "我们必须一直保持房间干净整洁。",
    appendInfo: ["main（主要）+tain(保持）——保持大体上的完好——维持，维修"],
  },
  {
    word: "effect",
    pronunciation: "/ɪ'fekt/",
    meaning: "v. 使发生；引起 n. 影响；结果",
    example: "dramatic/long-term effects",
    translation: "引人注目的影响；长期效应",
    appendInfo: [],
  },
  {
    word: "literature",
    pronunciation: "/ˈlɪtrətʃər/",
    meaning: "n. 文学；文献",
    example: "great works of literature",
    translation: "文学巨著",
    appendInfo: ["literary  adj.文学的 文化的"],
  },
  {
    word: "adapt",
    pronunciation: "/ə'dæpt/",
    meaning: "v. 使适应；改编",
    example: "These styles can be adapted to suit individual tastes.",
    translation: "这些式样可以修改，以适应个人不同爱好。",
    appendInfo: ["adapt sth./oneself to使(自己)适应", "adapt to…适应"],
  },
  {
    word: "technique",
    pronunciation: "/tek'niːk/",
    meaning: "n. 技术；技能",
    example: "The artist combines different techniques in the same painting.",
    translation: "",
    appendInfo: [
      "这两个名词均有“技术”之意。technique: 多指具体的某种技术和技巧。technology: 含义比technique广泛，泛指生产工艺、科学技术。",
    ],
  },
  {
    word: "disorder",
    pronunciation: "/dɪs'ɔːrdər/",
    meaning: "n. 杂乱，混乱；骚乱；紊乱，失调",
    example: "His financial affairs were in complete disorder.",
    translation: "他的钱财完全是一笔糊涂账。",
    appendInfo: ["dis+order=没有秩序=混乱"],
  },
  {
    word: "session",
    pronunciation: "/'seʃn/",
    meaning: "n. 会议；（法庭的）开庭；（进行某活动连续的）一段时间",
    example: "An emergency session was held to cope with this sudden attack.",
    translation: "将召开一场紧急的会议应对这一突然的袭击。",
    appendInfo: ["in session 在开会，在开庭"],
  },
  {
    word: "reinforce",
    pronunciation: "/ˌriːɪn'fɔːrs/",
    meaning: "v. 加强，加固；强化",
    example:
      "She reinforced her opinion that robots will never replace human beings.",
    translation: "她重申了她的观点，即机器人永远不会取代人类。",
    appendInfo: [
      "reinforcement：强化物",
      "re + in + force = 又 + in + 力量 =加固（再次增加力量）",
    ],
  },
  {
    word: "challenge",
    pronunciation: "/'tʃælɪndʒ/",
    meaning:
      "n. 挑战，考验； 挑战书；质询，质疑；异议 v. 质疑； 向…挑战；盘问；考验；拒绝，反对",
    example: "This career offers a challenge.",
    translation: "这份职业具有挑战性。",
    appendInfo: [" to challenge sb 向某人挑战"],
  },
  {
    word: "opportunity",
    pronunciation: "/ˌɑːpər'tuːnəti/",
    meaning: "n. 机会，良机",
    example:
      "The reporter grasped a rare opportunity to interview the president.",
    translation: "这名记者抓住了一次采访总统的珍贵机会。",
    appendInfo: ["opportunity knocks only once 千载难逢的机会"],
  },
  // 2026/2/6
  {
    word: "medium",
    pronunciation: "/'miːdiəm/",
    meaning: "adj. 适中的，中等的 n. 方法，媒介",
    example: "Do you mean the girl of medium height?",
    translation: "你是说那个中等身高的女孩吗？",
    appendInfo: [],
  },
  {
    word: "defeat",
    pronunciation: "/dɪ'fiːt/",
    meaning: "v. 击败, 战胜; 挫败; 使落空 n. 击败; 战败; 失败",
    example: "He defeated the champion in three sets.",
    translation: "他三盘击败了冠军。",
    appendInfo: ["successor and defeat 成败"],
  },
  {
    word: "outdo",
    pronunciation: "/ˌaʊt'duː/",
    meaning: "v. 超越，胜过",
    example: "He is ambitious to outdo everybody else in the class.",
    translation: "他立志超过班里的每一个人。",
    appendInfo: [],
  },
  {
    word: "calorie",
    pronunciation: "/'kæləri/",
    meaning: "n. 卡（路里）",
    example: "There are about 78 calories in an egg.",
    translation: "一个鸡蛋大约有78卡路里的热量。",
    appendInfo: [],
  },
  {
    word: "gear",
    pronunciation: "/ɡɪr/",
    meaning:
      "n. 排挡；齿轮；传动装置;（某种活动的）设备，用具；衣服 v. 用齿轮连接；（使）适合，使适应；（使）准备好 adj. 时髦的；好极了",
    example: "Careless use of the clutch may damage the gears.",
    translation: "离合器使用不慎可能会损坏传动装置。",
    appendInfo: ["out of gear 情绪失控"],
  },
  {
    word: "benefit",
    pronunciation: "/'benɪfɪt/",
    meaning: "n. 利益；好处 v. 有益于；得益",
    example: "The new regulations will be of benefit to everyone concerned.",
    translation: "新规章将使所有有关人员受益。",
    appendInfo: [
      "for the benefit of 为了...的利益。be of benefit to sb./sth. 对...有益",
    ],
  },
  {
    word: "spectrum",
    pronunciation: "/'spektrəm/",
    meaning: "n. 光谱，声谱，频谱；范围，幅度；系列，层次",
    example: "Red and violet are at opposite ends of the spectrum.",
    translation: "红色和紫色位于光谱的两端。",
    appendInfo: ["at both ends of the political spectrum “政治上的左右两派” "],
  },
  {
    word: "goal",
    pronunciation: "/ɡoʊl/",
    meaning: "n. 目标",
    example: "His goal is to find a job in an international company.",
    translation: "他的目标是找到一份在外企的工作。",
    appendInfo: ["指比较明确的，近期的目标。同义词：aim,end,purpose,objective"],
  },
  {
    word: "scale",
    pronunciation: "/skeɪl/",
    meaning: "n. 规模；刻度；级别；比例尺 v. 改变（图片等的）比例，缩放；攀登",
    example: "He wants to sell his goods on a larger scale.",
    translation: "他想在更大的规模上销售他的货物。",
    appendInfo: ["on a large scale大规模地，大范围地"],
  },
  {
    word: "expectation",
    pronunciation: "/ˌekspek'teɪʃn/",
    meaning: "n. 期待，期望，预期",
    example: "Her performance did not live up to our expectations.",
    translation: "她的表现没有达到我们的预期。",
    appendInfo: ["in expectation of...以期待。。。"],
  },
  {
    word: "motivate",
    pronunciation: "/'moʊtɪveɪt/",
    meaning: "v. 激励，激发积极性",
    example: "He's good at motivating students to work hard.",
    translation: "他很擅长激励学生努力学习。",
    appendInfo: ["motive n 动机", "motivated adj. 有积极性的"],
  },
  {
    word: "breed",
    pronunciation: "/briːd/",
    meaning: "n. 品种; 类型 v. 饲养; 繁殖; 养育, 教育; 酿成, 导致",
    example: "His horse is of the best breed.",
    translation: "他的马是最好的品种。",
    appendInfo: ["brood 孵蛋，沉思"],
  },
  {
    word: "emback",
    pronunciation: "/ɪm'bɑːrk/",
    meaning: "v. （使）上船或飞机；（使）从事",
    example: "After a short break, he was ready to embark on a new adventure.",
    translation: "在短暂休息之后，他做好了开始一段新冒险的准备。",
    appendInfo: ["embark on/upon 着手做"],
  },
  {
    word: "switch",
    pronunciation: "/swɪtʃ/",
    meaning:
      "v. 调换, 交换; 调动, 调任; 改变, 转变; 用开关把…开启(或关掉) n. 开关; 电闸; 改变, 转变; 道岔; 细软枝条",
    example: "The dates of the last two exams have been switched.",
    translation: "最后两门考试的日期调换了。",
    appendInfo: ["switch trade 转手贸易  "],
  },
  {
    word: "optimism",
    pronunciation: "/'ɑːptɪmɪzəm/",
    meaning: "n. 乐观；乐观主义",
    example:
      "At the beginning of her career she was full of optimism but not now.",
    translation: "她事业伊始十分乐观，但现在已今非昔比了。",
    appendInfo: ["pessimism悲观主义", "optim-是'best'的词根"],
  },
  // 2026/2/9
  {
    word: "client",
    pronunciation: "/'klaɪənt/",
    meaning: "n. 客户；委托人；当事人；客户端",
    example: "The company needs to focus on its biggest clients.",
    translation: "该公司需要将重点放在最大的客户上。",
    appendInfo: ["online client （银行的）网上客户  "],
  },
  {
    word: "perform",
    pronunciation: "/pərˈfɔːrm/",
    meaning: "v. 做, 进行; 演出, 表演; 执行, 履行; 工作; 运行; 表现",
    example: "She performs an important role in our organization.",
    translation: "她在我们的组织中发挥着重要的作用。",
    appendInfo: ["performance n.表演 -> perform 表演，执行"],
  },
  {
    word: "intensity",
    pronunciation: "/ɪn'tensəti/",
    meaning:
      "n. (思想、感情、活动等的)强烈, 剧烈, 紧张; (电、热、光等的)强度, 烈度; 色饱和度",
    example:
      "The intensity of heat from the sun can cause changes to our atmosphere.",
    translation: "太阳的强热可能会导致我们的大气层发生变化。",
    appendInfo: ["intense adj. 非常的, 紧张的, 强烈的"],
  },
  {
    word: "impact",
    pronunciation: "/'ɪmpækt/",
    meaning: "n. 影响，作用，冲击 v. 对…产生影响",
    example:
      "Discharging polluted water into the ocean will have an impact on environment.",
    translation: "把污水排放到海洋中会对环境产生影响。",
    appendInfo: ["影响Effect/Influence/Impact"],
  },
  {
    word: "individual",
    pronunciation: "/ˌɪndɪ'vɪdʒuəl/",
    meaning:
      "adj. 单独的，独有的；个别的；一个人（使用）的；独特的，与众不同的 n. 个人，个体；某种类型的人",
    example: "These styles can be adapted to suit individual tastes.",
    translation: "这些式样均可改动以适应个人不同的爱好。",
    appendInfo: [
      "注意：individual指个别的，独特的；private指秘密的，私下的；personal特指个人的，亲自的，涉及隐私的，own则为自有的，特有的",
    ],
  },
  {
    word: "sheer",
    pronunciation: "/ʃɪr/",
    meaning:
      "adj. 纯粹的，完全的；几乎垂直的，陡峭的 v. 突然变向 adj.（用来强调事物的大小、程度或数量）",
    example:
      "The area is under threat from the sheer number of tourists using it.",
    translation: "这一地区由于游客人数太多而面临威胁。",
    appendInfo: [
      "sheer away from sth. 避开",
      "shear v. 修剪",
      "The sheer scale of manufacture is so huge, that is the issue 问题在于生产规模过于巨大。",
    ],
  },
  {
    word: "apply",
    pronunciation: "/ə'plaɪ/",
    meaning: "v. 应用，使用；申请",
    example: "to apply to a company/university",
    translation: "向公司/大学申请",
    appendInfo: ["apply to适用于；申请 apply A to B 将A应用于B "],
  },
  {
    word: "crucial",
    pronunciation: "/'kruːʃl/",
    meaning: "adj. 至关重要的；决定性的",
    example:
      "The reform of the healthcare system became a topic of crucial importance in the presidential election debate.",
    translation: "医疗系统改革成了总统大选辩论中的至关重要的话题。",
    appendInfo: [
      "cruc(=cross十字)+ial:处于十字路口该选择何去何从- 关键的 至关重要的",
    ],
  },
  {
    word: "wrinkle",
    pronunciation: "/'rɪŋkl/",
    meaning: "n. 脸上的皱纹；皱褶，皱痕 v. 起皱纹；皱起；（使）起皱褶",
    example: "She's beginning to get wrinkles around her eyes.",
    translation: "她的眼角开始有皱纹了。",
    appendInfo: ["wrinkle-free没有皱折（衣服）"],
  },
  {
    word: "principle",
    pronunciation: "/'prɪnsəpl/",
    meaning: "n. 原则；原理",
    example: "I refuse to lie about it; it's against my principles .",
    translation: "我绝不为此事撒谎；那是违背我的原则的。",
    appendInfo: ["in principle 原则上; on principle 依据（自己的）道德准则"],
  },
  {
    word: "tough",
    pronunciation: "/tʌf/",
    meaning:
      "adj. 坚韧的; 牢固的; 不嫩的, 老的; 强壮的; 坚强的; 强硬的; 困难的, 艰苦的 v. 〈美俚〉忍耐困难 n. 恶棍; 暴徒; 粗暴的人",
    example: "a tough childhood",
    translation: "苦难的童年",
    appendInfo: ["tough it out [美国口语]勇敢地承受；坚持到底"],
  },
  {
    word: "feedback",
    pronunciation: "/'fiːdbæk/",
    meaning: "n. 反馈；反馈信息",
    example: "The feedback from your clients is crucial to improve your work.",
    translation: "客户的反馈对改善你们的工作至关重要。",
    appendInfo: [],
  },
  {
    word: "fairly",
    pronunciation: "/'ferli/",
    meaning: "adv. 相当；尚可；公平地",
    example: "I'm fairly sure that this is the right answer.",
    translation: "我相当肯定这就是正确答案。",
    appendInfo: ["fairly 和 rather 都表示 相当的，前者修饰褒义，后者修饰贬义"],
  },
  {
    word: "classical",
    pronunciation: "/'klæsɪkl/",
    meaning: "adj. 古典的，经典的",
    example: "the classical theory of unemployment",
    translation: "传统的失业理论",
    appendInfo: ["classic 最优秀的, 传统的, 古典的"],
  },
  // 2026/2/10
  {
    word: "simultaneously",
    pronunciation: "/ˌsaɪməl'teɪnjəsli/",
    meaning: "adv. 同时地",
    example: "Students answered the teacher's question simultaneously.",
    translation: "同学们同时回答了老师的问题。",
    appendInfo: ["simult-相同的+aneous-时间=同时的"],
  },
  {
    word: "split",
    pronunciation: "/splɪt/",
    meaning:
      "vt. (过去式&过去分词:split)劈开; 切开; 撕裂; 分担; 分得; 使分裂; 使不团结; [化]分解; [核]使产生核裂变 vi. 被劈开; 裂开; 被撕裂; 破裂; 分裂; 断绝关系; 打成平局 n. 劈开; 分割; 裂口; 裂缝; 分裂; 派系; 裂片; 薄片; 劈叉; 平局",
    example: "She split the class into groups of four.",
    translation: "她按四人一组把全班分成若干小组。",
    appendInfo: ["split up 分手"],
  },
  {
    word: "interfere",
    pronunciation: "/ˌɪntər'fɪr/",
    meaning: "v. 干预，干涉；妨碍",
    example: "I'm an adult now, so don't try to interfere with my decisions.",
    translation: "我是一个成年人了，所以别想着干涉我做决定。",
    appendInfo: [
      "interfere with sth ：1. 妨碍；干扰    2. 弄坏（器材等）",
      "【巧 记】inter（在……之间，在……之中，相互）+ fere.（伴侣，配偶）=在两个伴侣之间，干涉妨碍人家的生活。  ",
    ],
  },
  {
    word: "nerve",
    pronunciation: "/nɜːrv/",
    meaning: "n. 神经；勇气，胆量",
    example: "The man lit a cigarette to calm his nerves.",
    translation: "这个男人点燃了一支烟来稳定情绪。",
    appendInfo: ["have the nerve to do 敢于做"],
  },
  {
    word: "belief",
    pronunciation: "/bɪˈliːf/",
    meaning: "n. 信仰，信条；相信",
    example: "They refuse to eat meat because of religious beliefs.",
    translation: "因为宗教信仰，他们拒绝吃肉。",
    appendInfo: [
      "beyond belief 难以置信 have great belief in sb 非常信任某人 shake one's belief 改变某人的想法",
    ],
  },
  {
    word: "strategy",
    pronunciation: "/'strætədʒi/",
    meaning: "n. 战略，策略",
    example:
      "The company is considering a change in marketing strategies to regain its market share.",
    translation: "这家公司正在考虑转变营销策略，以重获市场份额。",
    appendInfo: ["strategist 战略家 谋士 军师家"],
  },
  {
    word: "regardless",
    pronunciation: "/rɪ'ɡɑːrdləs/",
    meaning: "adv. 不管，不顾；无论如何，不管怎样",
    example: "She set out to visit him regardless of the risk.",
    translation: "尽管有风险，她还是去探望他了。",
    appendInfo: [
      "regardless of 不管；不顾",
      "regard n注意，尊重，问候 vt注意，考虑，看待，尊敬 vi注意，注重，注视",
    ],
  },
  {
    word: "positive",
    pronunciation: "/'pɑːzətɪv/",
    meaning:
      "adj. 积极的, 乐观的, 正面的; 赞同的, 肯定的; 确信的; 绝对的; 正数的; 正极的; 阳性的 n. 优势, 优点; 阳性; 正极; 正数; 正片",
    example: "She tried to be more positive about her new job.",
    translation: "她力求对新工作更有信心。",
    appendInfo: [],
  },
  {
    word: "consist",
    pronunciation: "/kən'sɪst/",
    meaning: "v. 组成，构成；存在于",
    example:
      "His breakfast consisted of whole wheat bread and a glass of milk.",
    translation: "他的早餐由全麦面包和一杯牛奶组成。",
    appendInfo: ["consist of 由。。。组成"],
  },
  // 2026/3/3
  {
    word: "anxious",
    pronunciation: "/'æŋkʃəs/",
    meaning: "adj. 渴望的；忧虑的",
    example: "Parents are naturally anxious for their children.",
    translation: "父母自然为儿女担心。",
    appendInfo: ["anxious for sth. 渴望有(得到)"],
  },
  {
    word: "revise",
    pronunciation: "/rɪ'vaɪz/",
    meaning: "v. 修订，修正；复习，温习",
    example:
      "The investigation team has to revise the original plan due to local objections.",
    translation: "由于来自当地的反对，这支考察队不得不修改最初的计划。",
    appendInfo: ["re- 重新 vis-看 revised 经过校正/修订的"],
  },
  {
    word: "transfer",
    pronunciation: "/træns'fɜː(r)/",
    meaning: "v. 转移，调转，调任 n. 迁移，移动",
    example: "I am going to transfer some money to your account.",
    translation: "我会转些钱到你的账户上。",
    appendInfo: ["transfer...to... 把...转移/调任到..."],
  },
  {
    word: "diminish",
    pronunciation: "",
    meaning: "v. 减少，减弱，降低；贬低，贬损；轻视",
    example: "",
    translation: "",
    appendInfo: [],
  },
  {
    word: "therefore",
    pronunciation: "",
    meaning: "adv.因此，所以",
    example: "",
    translation: "",
    appendInfo: [],
  },
  {
    word: "significance",
    pronunciation: "",
    meaning: "n.意义, 含义; 重要性; 显著性",
    example: "",
    translation: "",
    appendInfo: [],
  },
  // 2026/3/4
  {
    word: "",
    pronunciation: "",
    meaning: "",
    example: "",
    translation: "",
    appendInfo: [],
  },
  {
    word: "",
    pronunciation: "",
    meaning: "",
    example: "",
    translation: "",
    appendInfo: [],
  },
  {
    word: "",
    pronunciation: "",
    meaning: "",
    example: "",
    translation: "",
    appendInfo: [],
  },
  {
    word: "",
    pronunciation: "",
    meaning: "",
    example: "",
    translation: "",
    appendInfo: [],
  },
  {
    word: "",
    pronunciation: "",
    meaning: "",
    example: "",
    translation: "",
    appendInfo: [],
  },
  {
    word: "",
    pronunciation: "",
    meaning: "",
    example: "",
    translation: "",
    appendInfo: [],
  },
  {
    word: "",
    pronunciation: "",
    meaning: "",
    example: "",
    translation: "",
    appendInfo: [],
  },
  {
    word: "",
    pronunciation: "",
    meaning: "",
    example: "",
    translation: "",
    appendInfo: [],
  },
  {
    word: "",
    pronunciation: "",
    meaning: "",
    example: "",
    translation: "",
    appendInfo: [],
  },
  {
    word: "",
    pronunciation: "",
    meaning: "",
    example: "",
    translation: "",
    appendInfo: [],
  },
];

export default englishWords;
